# https://golangci-lint.run/usage/linters/
linters:
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
#    - funlen
    - gci
#    - gochecknoglobals
    - gochecknoinits
    - gocognit
#    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
#    - goerr113
    - gofumpt
    - goheader
#    - goimports # inconsistent with gci
    - gomnd
    - gomoddirectives
#    - gomodguard # no need
    - goprintffuncname
    - gosec
    - grouper
    - ifshort
    - importas
#    - ireturn # TODO revisit
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
