version: "3"

tasks:
  install-tools:
    desc: install tools
    cmds:
      - go install mvdan.cc/gofumpt@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/goreleaser/goreleaser@latest
      - go install github.com/daixiang0/gci@latest
      - go install github.com/caarlos0/svu@latest

  fmt:
    desc: format code
    vars:
      MODULE:
        sh: head -n 1 go.mod | cut -d' ' -f2
    cmds:
      - go mod tidy
      - gci write -s standard -s default -s "prefix({{.MODULE}})" .
      - gofumpt -w -l .
      - golangci-lint run --fix ./...

  lint:
    desc: lint code
    cmds:
      - golangci-lint run ./...
      - helm lint helm/pv-migrate
      - goreleaser check

  clean:
    desc: clean
    cmds:
      - rm -rf {{.ROOT_DIR}}/dist/

  build:
    desc: build
    cmds:
      - goreleaser build --snapshot --rm-dist --single-target

  release:
    desc: release
    vars:
      NUM_LAST_TAGS: 3
      LAST_TAGS:
        sh: git tag --sort=-version:refname | head -n {{.NUM_LAST_TAGS}} | xargs echo
      NEXT_TAG:
        sh: svu next
    cmds:
      - "echo Last {{.NUM_LAST_TAGS}} tags: {{.LAST_TAGS}}"
      - "echo Next tag: {{.NEXT_TAG}}"
      - git tag -a {{.NEXT_TAG}} -m "Release {{.NEXT_TAG}}"
      - git push origin {{.NEXT_TAG}}
