version: "3"

tasks:
  fmt:
    desc: format code
    cmds:
      - go mod tidy
      - gci write -s standard -s default -s "prefix(github.com/utkuozdemir/pv-migrate)" .
      - gofumpt -w -l .

  lint:
    desc: lint code
    cmds:
      - golangci-lint run ./...
      - helm lint helm/pv-migrate

  update-chart:
    desc: Update the Helm chart
    cmds:
      - helm-docs -c helm/pv-migrate/
      - helm package helm/pv-migrate/
      - mv pv-migrate-*.tgz internal/migrator/helm-chart.tgz

  release:
    desc: Create a new tag
    vars:
      NEXT:
        sh: svu n
    cmds:
      - git tag {{.NEXT}}
      - echo {{.NEXT}}
      - git push origin {{.NEXT}}
