# -- String to partially override the fullname template with a string (will prepend the release name)
nameOverride: ""
# -- String to fully override the fullname template with a string
fullnameOverride: ""

sshd:
  # -- Enable SSHD server deployment
  enabled: false
  image:
    # -- SSHD image repository
    repository: docker.io/utkuozdemir/pv-migrate-sshd
    # -- SSHD image pull policy
    pullPolicy: IfNotPresent
    # -- SSHD image tag
    tag: 1.0.0
  # -- SSHD image pull secrets
  imagePullSecrets: []
  serviceAccount:
    # -- Create a service account for SSHD
    create: true
    # -- SSHD service account annotations
    annotations: {}
    # -- SSHD service account name to use
    name: ""
  # -- SSHD pod annotations
  podAnnotations: {}
  # -- SSHD pod security context
  podSecurityContext: {}
  # -- SSHD deployment security context
  securityContext:
    capabilities:
      add:
      - CAP_SYS_CHROOT
  service:
    # -- SSHD service type
    type: ClusterIP
    # -- SSHD service port
    port: 22
    # -- SSHD service annotations
    annotations: {}
    # -- SSHD service load balancer IP
    loadBalancerIP: ""
  # -- SSHD pod resources
  resources: {}
  # -- The node name to schedule SSHD pod on
  nodeName: ""
  # -- SSHD node selector
  nodeSelector: {}
  # -- SSHD pod tolerations
  # @default -- see [values.yaml](values.yaml)
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  # -- SSHD pod affinity
  affinity: {}

  # -- Mount a public key into the SSHD pod
  publicKeyMount: true
  # -- The path to mount the public key
  publicKeyMountPath: /root/.ssh/authorized_keys
  # -- The public key content
  publicKey: ""

  # -- Mount a private key into the SSHD pod
  privateKeyMount: false
  # -- The path to mount the private key
  privateKeyMountPath: /root/.ssh/id_ed25519
  # -- The private key content
  privateKey: ""

  # -- Namespace to run SSHD pod in
  namespace: ""
  # -- PVC mounts into the SSHD pod. For examples, see see [values.yaml](values.yaml)
  pvcMounts: []
    #- name: pvc-1
    #  readOnly: false
    #  mountPath: /source
    #- name: pvc-2
    #  readOnly: true
    #  mountPath: /dest

rsync:
  # -- Enable creation of Rsync job
  enabled: false
  image:
    # -- Rsync image repository
    repository: docker.io/utkuozdemir/pv-migrate-rsync
    # -- Rsync image pull policy
    pullPolicy: IfNotPresent
    # -- Rsync image tag
    tag: 1.0.0
  # -- Rsync image pull secrets
  imagePullSecrets: []
  serviceAccount:
    # -- Create a service account for Rsync
    create: true
    # -- Rsync service account annotations
    annotations: {}
    # -- Rsync service account name to use
    name: ""
  # -- Rsync pod annotations
  podAnnotations: {}
  # -- Rsync pod security context
  podSecurityContext: {}
  # -- Rsync deployment security context
  securityContext: {}
  # -- Rsync pod resources
  resources: {}
  # -- The node name to schedule Rsync pod on
  nodeName: ""
  # -- Rsync node selector
  nodeSelector: {}
  # -- Rsync pod tolerations
  # @default -- see [values.yaml](values.yaml)
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  # -- Rsync pod affinity
  affinity: {}
  # Rsync job restart policy
  restartPolicy: Never
  # Rsync job backoff limit
  backoffLimit: 0

  # -- Mount a private key into the Rsync pod
  privateKeyMount: false
  # -- The path to mount the private key
  privateKeyMountPath: /root/.ssh/id_ed25519
  # -- The private key content
  privateKey: ""
  # -- Full Rsync command and flags
  command: ""

  # -- Namespace to run Rsync pod in
  namespace: ""
  # -- PVC mounts into the Rsync pod. For examples, see see [values.yaml](values.yaml)
  pvcMounts: []
    #- name: pvc-1
    #  readOnly: false
    #  mountPath: /source
    #- name: pvc-2
    #  readOnly: true
    #  mountPath: /dest
