{{- if .Values.rsync.enabled -}}
{{- if .Values.rsync.privateKeyMount -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pv-migrate.fullname" . }}-rsync
  namespace: {{ .Values.dest.namespace }}
  labels:
    app.kubernetes.io/component: rsync
    {{- include "pv-migrate.labels" . | nindent 4 }}
data:
  privateKey: {{ (required "rsync.privateKey is required!" .Values.rsync.privateKey) | b64enc | quote }}
type: Opaque
{{- end }}
{{- end }}
