{{- if .Values.sshd.enabled -}}
{{- if or .Values.sshd.publicKeyMount .Values.sshd.privateKeyMount -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pv-migrate.fullname" . }}-sshd
  namespace: {{ .Values.sshd.namespace }}
  labels:
    app.kubernetes.io/component: sshd
    {{- include "pv-migrate.labels" . | nindent 4 }}
data:
  {{- if .Values.sshd.publicKeyMount }}
  publicKey: {{ (required "sshd.publicKey is required!" .Values.sshd.publicKey) | b64enc | quote }}
  {{- end }}
  {{- if .Values.sshd.privateKeyMount }}
  privateKey: {{ (required "sshd.privateKey is required!" .Values.sshd.privateKey) | b64enc | quote }}
  {{- end }}
type: Opaque
{{- end }}
{{- end }}
