{{- if .Values.sshd.enabled -}}
{{- if .Values.sshd.publicKeyMount -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pv-migrate.fullname" . }}-sshd
  namespace: {{ .Values.source.namespace }}
  labels:
    app.kubernetes.io/component: sshd
    {{- include "pv-migrate.labels" . | nindent 4 }}
data:
  publicKey: {{ (required "sshd.publicKey is required!" .Values.sshd.publicKey) | b64enc | quote }}
type: Opaque
{{- end }}
{{- end }}
