{{- if .Values.sshd.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pv-migrate.fullname" . }}-sshd
  namespace: {{ .Values.source.namespace }}
  labels:
    app.kubernetes.io/component: sshd
    {{- include "pv-migrate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sshd.service.type }}
  ports:
    - port: {{ .Values.sshd.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: sshd
    {{- include "pv-migrate.selectorLabels" . | nindent 4 }}
{{- end }}
