{{- if .Values.sshd.enabled -}}
{{- if .Values.sshd.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pv-migrate.sshd.serviceAccountName" . }}
  namespace: {{ .Values.source.namespace }}
  labels:
    app.kubernetes.io/component: sshd
    {{- include "pv-migrate.labels" . | nindent 4 }}
  {{- with .Values.sshd.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
