rsync:
  enabled: true
  nodeName: porcupine
  mountSource: true

source:
  namespace: pv-migrate-test-1
  pvcName: pv-migrate-test-source-1
  pvcMountReadOnly: true
  path: /

dest:
  namespace: pv-migrate-test-1
  pvcName: pv-migrate-test-dest-1
  path: /
