rsync:
  enabled: true
  deleteExtraneousFiles: false
  noChown: false
  privateKeyMount: true
  privateKeyMountPath: /root/.ssh/id_ed25519
  privateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz
    c2gtZWQyNTUxOQAAACCw++RvFPODUxObjYsfZe1IFA8FdB8bfwYSdAjo3iEz3QAA
    AIiKNGNUijRjVAAAAAtzc2gtZWQyNTUxOQAAACCw++RvFPODUxObjYsfZe1IFA8F
    dB8bfwYSdAjo3iEz3QAAAEDEOri9qDz2wm/UupFAY7ipERgoNDNXyhd/cDI5lmxv
    ZLD75G8U84NTE5uNix9l7UgUDwV0Hxt/BhJ0COjeITPdAAAAAAECAwQF
    -----END OPENSSH PRIVATE KEY-----

sshd:
  enabled: true
  publicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILD75G8U84NTE5uNix9l7UgUDwV0Hxt/BhJ0COjeITPd

source:
  namespace: pv-migrate-test-1
  pvcName: pv-migrate-test-source-1
  pvcMountReadOnly: true
  path: /

dest:
  namespace: pv-migrate-test-2
  pvcName: pv-migrate-test-dest-2
  path: /
