---
name: build sshd image

on:
  push:
    branches:
      - master
      - renovate/**
    paths:
      - docker/sshd/**
  pull_request:
    branches:
      - master
    paths:
      - docker/sshd/**

jobs:
  build-sshd-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.6.0
      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: utkuozdemir
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4.1.0
        with:
          context: ./docker/sshd/
          platforms: linux/amd64,linux/arm,linux/arm64
          push: true
          tags: docker.io/utkuozdemir/pv-migrate-sshd:latest
