---
name: debug-build
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "img/**"
      - "test/**"
      - ".gitignore"
      - "docker/**"
      - "helm/**"
      - "renovate.json"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "img/**"
      - "test/**"
      - ".gitignore"
      - "docker/**"
      - "helm/**"
      - "renovate.json"
jobs:
  debug-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Go
        uses: actions/setup-go@v2.1.4
        with:
          # renovate: go
          go-version: 1.17
      - name: Install go-acc
        # renovate: go-acc
        run: go install github.com/ory/go-acc@v0.2.6
      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
          NGROK_REGION: eu
      - name: Set nf_conntrack_max for kind
        run: sudo sysctl net/netfilter/nf_conntrack_max=131072
      - name: Run tests
        run: go-acc --output profile.cov ./... -- -v -timeout 20m
      - name: Don't kill instance
        if: ${{ failure() }}
        run: sleep 1h
