---
name: Release rsync image
on:
  push:
    tags:
      - docker-rsync-*
jobs:
  release-rsync-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: utkuozdemir
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set image tag as env variable
        run: echo "IMAGE_VERSION=$(echo ${GITHUB_REF#refs/*/} | sed 's/^docker-rsync-//')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./docker/rsync/
          platforms: linux/amd64,linux/arm,linux/arm64
          push: true
          tags: |
            docker.io/utkuozdemir/pv-migrate-rsync:latest
            docker.io/utkuozdemir/pv-migrate-rsync:${{ env.IMAGE_VERSION }}
