---
name: release sshd image

on:
  push:
    tags:
      - docker-sshd-*

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: utkuozdemir
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set image tag as env variable
        run: echo "IMAGE_VERSION=$(echo ${GITHUB_REF#refs/*/} | sed 's/^docker-sshd-//')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./docker/sshd/
          platforms: linux/amd64,linux/arm,linux/arm64
          push: true
          tags: |
            docker.io/utkuozdemir/pv-migrate-sshd:latest
            docker.io/utkuozdemir/pv-migrate-sshd:${{ env.IMAGE_VERSION }}
